name: Java CI for LatestCucumberParallelExecutionUsingTestNG

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout LatestCucumberParallelExecutionUsingTestNG repository
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Step 4: Run Maven build and tests
      - name: Build and run tests
        run: mvn clean install

      # Step 5: Publish test results (if any reports exist)
      - name: Archive test reports
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./SparkReport/Index.html
